# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
on:
  push:
    branches: main

name: Download tweets

jobs:
  build:
    environment: Twitter developer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install curl headers
        run: sudo apt-get install libcurl4-openssl-dev

      - uses: r-lib/actions/setup-renv@v2

      - name: Run script
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: Rscript R/scrape-tidytuesday.R
